### ISSUE TITLE
[Chore] Code formatting

### ISSUE THREAD

**Issue by evereq** [ever-co/ever-teams#1687] opened 2023-10-30 12:10 UTC
We need to make sure all prettier / formatting working well.

Here are the differences between the prettier config files in Ever Gauzy and Ever Teams projects:

```
.prettierrc file:

different properties value:
- tabWidth: (teams: 2) (gauzy: 4)

properties exist in Gauzy and don't exist in Teams .prettierrc file:
(
  "printWidth": 120,
  "semi": true,
  "arrowParens": "always",
  "quoteProps": "as-needed",
  "trimTrailingWhitespace": true,
  "overrides": [
		{
			"files": "*.scss",
			"options": {
				"useTabs": false,
				"tabWidth": 2
			}
		},
		{
			"files": "*.yml",
			"options": {
				"useTabs": false,
				"tabWidth": 2
			}
		}
	]
)

.prettierignore file:

properties exist in Gauzy and don't exist in Teams .prettierrc files:
- gauzy: **/xplat/*/.xplatframework
```

**Comment by Anishali2** [comment] 2024-02-18 12:30
Can i make a change in husky
when user try to commit prettier will check and fix all the formatting issues in the full web files 
but the issue is husky is configured in the whole app so if someone from mobile app side commit then husky will again format and fix the files of web

**Comment by Anishali2** [comment] 2024-04-07 00:21
Sir, I'm closing this issue because it is fixed https://github.com/ever-co/ever-teams/pull/2198/files
I've added the linting prettier config so that on save the file will be formatted as per styling.

**Closed by Anishali2** 2024-04-07 00:21 UTC
Labels: devops, GitHub, Gauzy
