### ISSUE TITLE
[Bug] Static Task Status 

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2409] opened 2024-04-24 13:57 UTC
In the settings defined set of Statuses for that define the status for each task within a project/team

Status is a static value for each task, so for task status is the same for all pages and even other applications with have integration with Gauzy Teams.

Kanban board has columns that are strictly defined by Status.
it has as many columns as many statuses are.

The only exception is 'Backlog' column which contains all tasks (in settings should be able to ON/OFF)

Example: 

On the main page task 2 has 'In Progress' status 

<img width="1485" alt="Screenshot at Apr 24 15-54-19" src="https://github.com/ever-co/ever-teams/assets/107203576/c8b26876-0286-4843-b962-5fa268bd43c7">

On the Kanban task 2 has 'Open' status - in columns 'Open' is it totally wrong should be 'In prgress'

<img width="1062" alt="Screenshot at Apr 24 15-56-26" src="https://github.com/ever-co/ever-teams/assets/107203576/544d4040-88df-48ce-ac23-b09297b48fae">

**Comment by Anishali2** [comment] 2024-04-24 19:53
Sir @KostyaEver The kanban status is correct now let me explain 

Previously we only saved the status name of the task and not save the id 
before = `example: task = { ... status: "opened", taskStatusId: null }`
after = `example: task = { ... status: "opened", taskStatusId: "fd5bb9ab-b7bb-4a44-859f-9486d55ac874" }`

so we can say that the status works perfectly in the kanban board and may conflict in other sections of the app https://github.com/ever-co/ever-teams/pull/2361 this is the PR that fixed the issue.

**Comment by evereq** [comment] 2024-04-25 20:12
@KostyaEver / @Anishali2 so in my understand for NEWLY created tasks it should all work well, @KostyaEver can you confirm and we can close this issue?

**Comment by Anishali2** [comment] 2024-04-25 20:49
> @KostyaEver / @Anishali2 so in my understanding for NEWLY created tasks it should all work well, @KostyaEver can you confirm so we can close this issue?

Yes Sir this is resolved I think you asked for Rahul to migrate the status name with their according IDs so that this issue will not happen in the existing tasks also

**Comment by KostyaEver** [comment] 2024-04-26 07:19
Please once it works send demo video @Anishali2 to see

**Comment by evereq** [comment] 2024-04-26 08:39
@KostyaEver re-read what I write above please, you misunderstand. Nothing done for this, what @Anishali2 saying is that it works already well, but for NEWLY created issues. Can you check and confirm!?

**Comment by KostyaEver** [comment] 2024-04-29 08:42
Hi guys,
Here are two things either 
1. @evereq changes flow how it should be working and I don't understand
2. OR @Anishali2 does not fully understand how it should be working


Kanban has columns - each Column is a Status (we have in Settings a defined set of Statuses so that the user can set per task)

So if the user selects a status of a task, the task should appear in the corresponding column (selected status) . and the same status for this task will be for all over the app/page etc

Example:

Task 13 - On the dashboard page I started tracking the time and the status was changed to 'In progress' automatically as you can see on the picture

<img width="1626" alt="Screenshot at Apr 29 10-24-50" src="https://github.com/ever-co/ever-teams/assets/107203576/718409a5-b24f-49b7-ad0c-01895dfd48f4">

then I open Kanban and I see that the task 13 is still in column 'Open' which is totally wrong

<img width="758" alt="Screenshot at Apr 29 10-24-04" src="https://github.com/ever-co/ever-teams/assets/107203576/0c004234-2e94-4e01-91c5-ff1dd84626d3">

On dashboard page in continuation of the proof the issue exists. I stopped tracking and changed the task status to 'Ready to Review'

<img width="1645" alt="Screenshot at Apr 29 10-25-53" src="https://github.com/ever-co/ever-teams/assets/107203576/87da65fa-a077-445e-a789-0b4054575677">


Again Kanban - the task must be in 'Ready for Review' column, but stays in 'Open'

<img width="1255" alt="Screenshot at Apr 29 10-26-25" src="https://github.com/ever-co/ever-teams/assets/107203576/2ed0aa11-1acf-431d-88c3-7b57c30d670b">


Please, let me know what do you think @evereq @Anishali2

**Comment by evereq** [comment] 2024-04-29 13:05
@KostyaEver you explained it exactly how it should work and I did NOT changed any requirements / flows :) 
Basically Kanban board should be in sync with all other views :) 
What I tried to communicate is that for OLD (existed) tasks it might NOT work well because there were some changes related to status! So in order to test all of that, you should create NEW tasks and in such case it suppose to work. If it does not work for NEWLY created tasks, it means that there are bugs that should be fixed by @Anishali2 . If it will work for all newly created tasks, but fail for some old tasks, it's FINE, we can ignore those issues etc.

Does it makes sense?

**Comment by KostyaEver** [comment] 2024-04-29 13:18
sure, Honestly I don't have access from the old teams etc. That's why the oldest that I have is the previous Monday.

All teams and tasks are NEWLY created. that means that it does NOT work as expected Let's fix it @Anishali2 

CC: @evereq

**Comment by Anishali2** [comment] 2024-04-30 20:43
Sir, I don't know how this issue is happening again on your end. I previously fixed this, but it seems to have reoccurred.

To help me identify the problem would it be possible for you to create a video of the issue?

I've attached the video of creating a task that is working just fine without making any changes to the code.


[Apex_1714508720841.webm](https://github.com/ever-co/ever-teams/assets/105014311/aa8de040-1a6d-491f-ae37-8579b3221930)

**Comment by KostyaEver** [comment] 2024-05-06 06:44
Hi @Anishali2 

Here is a video (Safari). The issues exists

https://www.loom.com/share/2129e0e5fb294d34b3194c3baa69b783?sid=8b2ad060-f311-4b32-9c4c-8157e6bdfcd5

**Comment by KostyaEver** [comment] 2024-05-09 06:32
User should NOT set any status - there should be a default status when the user creates an issue like 'open' or 'todo' etc.

One more video https://www.loom.com/share/47003731b570468dbe584df6c4060325?sid=be29caf7-eceb-449c-baf7-17989f930df4

@Anishali2

**Comment by KostyaEver** [comment] 2024-05-12 08:51
Just tested in Chrome, the same issue, it does not change the column for tasks with different statuses, keeps only for 'Open' status even with different status

https://www.loom.com/share/11258ebbf477436d9ceeb4a6f94927e9?sid=b5abb2d3-0f9a-44ab-84f5-5d3e32cef5df

@Anishali2 

@evereq Anish can't solve the issue we can sk anyone else to test 1st and can reproduce the same and then fix.

**Comment by evereq** [comment] 2024-05-12 10:14
But ... Did you test it with NEWLY created tasks? Also, maybe makes sense to delete statuses and recreate them in Settings? (of course in the TEST Team, not in our main!). Again, I think an issue is that you @KostyaEver somehow testing with OLD records (e.g. Status records or Tasks).

**Comment by KostyaEver** [comment] 2024-06-12 12:43
Just tested in the newly created Team and newly created task on Chrome and Safari

The issue persists. on Kanban task with status 'in progress' still is in column 'Open' (must be in 'in progress')

video: https://www.loom.com/share/a1e5600544ba40c58da7c943e9b31b98?sid=4d4b26a1-2afc-491a-a13b-db1696402ed5

@evereq

**Comment by evereq** [comment] 2024-06-12 13:56
@GloireMutaliko21 can you test that issue and try to fix it please? We had @Anishali2 working on this, but seems he can't reproduce issue, maybe you will be able to reproduce and fix it on your PC?

**Comment by GloireMutaliko21** [comment] 2024-06-12 14:02
Sir @evereq I will work on it. Is it high priority or I can first finish features I'm working on ?

**Comment by evereq** [comment] 2024-06-12 14:03
First finish what you working on and next move to this please @GloireMutaliko21

**Closed** 2024-06-14 11:06 UTC
Labels: bug, WEB, Ever Teams
